[build]
  command = "npm install --legacy-peer-deps && npm run build && cd netlify/functions && npm install --legacy-peer-deps"
  publish = "dist"
  functions = "netlify/functions"

[build.environment]
  NODE_VERSION = "18"

[functions]
  node_bundler = "none"
  included_files = ["dist/**", "netlify/functions/node_modules/**"]

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/server"
  status = 200

